"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
from . import session_pb2
import typing
import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _NiXnetSocketAttribute:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NiXnetSocketAttributeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NiXnetSocketAttribute.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NIXNETSOCKET_ATTRIBUTE_UNSPECIFIED: _NiXnetSocketAttribute.ValueType

class NiXnetSocketAttribute(_NiXnetSocketAttribute, metaclass=_NiXnetSocketAttributeEnumTypeWrapper):
    pass
NIXNETSOCKET_ATTRIBUTE_UNSPECIFIED: NiXnetSocketAttribute.ValueType
global___NiXnetSocketAttribute = NiXnetSocketAttribute

class _AddressFamily:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AddressFamilyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AddressFamily.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADDRESS_FAMILY_UNSPECIFIED: _AddressFamily.ValueType
    ADDRESS_FAMILY_INET: _AddressFamily.ValueType
    ADDRESS_FAMILY_INET6: _AddressFamily.ValueType

class AddressFamily(_AddressFamily, metaclass=_AddressFamilyEnumTypeWrapper):
    pass
ADDRESS_FAMILY_UNSPECIFIED: AddressFamily.ValueType
ADDRESS_FAMILY_INET: AddressFamily.ValueType
ADDRESS_FAMILY_INET6: AddressFamily.ValueType
global___AddressFamily = AddressFamily

class _GetAddrInfoFlags:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GetAddrInfoFlagsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GetAddrInfoFlags.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GET_ADDR_INFO_FLAGS_UNSPECIFIED: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_PASSIVE: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_CANONNAME: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_NUMERICHOST: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_NUMERICSERV: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_V4MAPPED: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_ALL: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_ADDRCONFIG: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_LOCALQUERY: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_PREFER_V4: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_UNICAST_REPLY: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_SHARED_RRSET: _GetAddrInfoFlags.ValueType
    GET_ADDR_INFO_FLAGS_BYPASS_CACHE: _GetAddrInfoFlags.ValueType

class GetAddrInfoFlags(_GetAddrInfoFlags, metaclass=_GetAddrInfoFlagsEnumTypeWrapper):
    pass
GET_ADDR_INFO_FLAGS_UNSPECIFIED: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_PASSIVE: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_CANONNAME: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_NUMERICHOST: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_NUMERICSERV: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_V4MAPPED: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_ALL: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_ADDRCONFIG: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_LOCALQUERY: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_PREFER_V4: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_UNICAST_REPLY: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_SHARED_RRSET: GetAddrInfoFlags.ValueType
GET_ADDR_INFO_FLAGS_BYPASS_CACHE: GetAddrInfoFlags.ValueType
global___GetAddrInfoFlags = GetAddrInfoFlags

class _GetNameInfoFlags:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GetNameInfoFlagsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GetNameInfoFlags.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GET_NAME_INFO_FLAGS_UNSPECIFIED: _GetNameInfoFlags.ValueType
    GET_NAME_INFO_FLAGS_NOFQDN: _GetNameInfoFlags.ValueType
    GET_NAME_INFO_FLAGS_NUMERICHOST: _GetNameInfoFlags.ValueType
    GET_NAME_INFO_FLAGS_NAMEREQD: _GetNameInfoFlags.ValueType
    GET_NAME_INFO_FLAGS_NUMERICSERV: _GetNameInfoFlags.ValueType
    GET_NAME_INFO_FLAGS_DGRAM: _GetNameInfoFlags.ValueType

class GetNameInfoFlags(_GetNameInfoFlags, metaclass=_GetNameInfoFlagsEnumTypeWrapper):
    pass
GET_NAME_INFO_FLAGS_UNSPECIFIED: GetNameInfoFlags.ValueType
GET_NAME_INFO_FLAGS_NOFQDN: GetNameInfoFlags.ValueType
GET_NAME_INFO_FLAGS_NUMERICHOST: GetNameInfoFlags.ValueType
GET_NAME_INFO_FLAGS_NAMEREQD: GetNameInfoFlags.ValueType
GET_NAME_INFO_FLAGS_NUMERICSERV: GetNameInfoFlags.ValueType
GET_NAME_INFO_FLAGS_DGRAM: GetNameInfoFlags.ValueType
global___GetNameInfoFlags = GetNameInfoFlags

class _IPProtocol:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IPProtocolEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IPProtocol.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IP_PROTOCOL_IP: _IPProtocol.ValueType
    IP_PROTOCOL_TCP: _IPProtocol.ValueType
    IP_PROTOCOL_UDP: _IPProtocol.ValueType
    IP_PROTOCOL_IPV6: _IPProtocol.ValueType

class IPProtocol(_IPProtocol, metaclass=_IPProtocolEnumTypeWrapper):
    pass
IP_PROTOCOL_IP: IPProtocol.ValueType
IP_PROTOCOL_TCP: IPProtocol.ValueType
IP_PROTOCOL_UDP: IPProtocol.ValueType
IP_PROTOCOL_IPV6: IPProtocol.ValueType
global___IPProtocol = IPProtocol

class _IPStackInfoStringFormat:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IPStackInfoStringFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IPStackInfoStringFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IPSTACK_INFO_STR_FORMAT_JSON: _IPStackInfoStringFormat.ValueType
    IPSTACK_INFO_STR_FORMAT_TEXT: _IPStackInfoStringFormat.ValueType

class IPStackInfoStringFormat(_IPStackInfoStringFormat, metaclass=_IPStackInfoStringFormatEnumTypeWrapper):
    pass
IPSTACK_INFO_STR_FORMAT_JSON: IPStackInfoStringFormat.ValueType
IPSTACK_INFO_STR_FORMAT_TEXT: IPStackInfoStringFormat.ValueType
global___IPStackInfoStringFormat = IPStackInfoStringFormat

class _OperationalStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationalStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OperationalStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPERATIONAL_STATUS_DOWN: _OperationalStatus.ValueType
    OPERATIONAL_STATUS_UP: _OperationalStatus.ValueType

class OperationalStatus(_OperationalStatus, metaclass=_OperationalStatusEnumTypeWrapper):
    pass
OPERATIONAL_STATUS_DOWN: OperationalStatus.ValueType
OPERATIONAL_STATUS_UP: OperationalStatus.ValueType
global___OperationalStatus = OperationalStatus

class _OptName:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OptNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OptName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPT_NAME_UNSPECIFIED: _OptName.ValueType
    OPT_NAME_TCP_NODELAY: _OptName.ValueType
    OPT_NAME_IP_ADD_MEMBERSHIP: _OptName.ValueType
    OPT_NAME_IP_DROP_MEMBERSHIP: _OptName.ValueType
    OPT_NAME_IP_MULTICAST_IF: _OptName.ValueType
    OPT_NAME_IP_MULTICAST_TTL: _OptName.ValueType
    OPT_NAME_IPV6_JOIN_GROUP: _OptName.ValueType
    OPT_NAME_IPV6_LEAVE_GROUP: _OptName.ValueType
    OPT_NAME_IPV6_ADD_MEMBERSHIP: _OptName.ValueType
    OPT_NAME_IPV6_DROP_MEMBERSHIP: _OptName.ValueType
    OPT_NAME_IPV6_MULTICAST_IF: _OptName.ValueType
    OPT_NAME_IPV6_MULTICAST_HOPS: _OptName.ValueType
    OPT_NAME_IPV6_V6ONLY: _OptName.ValueType
    OPT_NAME_SO_RXDATA: _OptName.ValueType
    OPT_NAME_SO_RCVBUF: _OptName.ValueType
    OPT_NAME_SO_SNDBUF: _OptName.ValueType
    OPT_NAME_SO_NONBLOCK: _OptName.ValueType
    OPT_NAME_SO_BINDTODEVICE: _OptName.ValueType
    OPT_NAME_SO_ERROR: _OptName.ValueType
    OPT_NAME_SO_LINGER: _OptName.ValueType
    OPT_NAME_SO_REUSEADDR: _OptName.ValueType

class OptName(_OptName, metaclass=_OptNameEnumTypeWrapper):
    pass
OPT_NAME_UNSPECIFIED: OptName.ValueType
OPT_NAME_TCP_NODELAY: OptName.ValueType
OPT_NAME_IP_ADD_MEMBERSHIP: OptName.ValueType
OPT_NAME_IP_DROP_MEMBERSHIP: OptName.ValueType
OPT_NAME_IP_MULTICAST_IF: OptName.ValueType
OPT_NAME_IP_MULTICAST_TTL: OptName.ValueType
OPT_NAME_IPV6_JOIN_GROUP: OptName.ValueType
OPT_NAME_IPV6_LEAVE_GROUP: OptName.ValueType
OPT_NAME_IPV6_ADD_MEMBERSHIP: OptName.ValueType
OPT_NAME_IPV6_DROP_MEMBERSHIP: OptName.ValueType
OPT_NAME_IPV6_MULTICAST_IF: OptName.ValueType
OPT_NAME_IPV6_MULTICAST_HOPS: OptName.ValueType
OPT_NAME_IPV6_V6ONLY: OptName.ValueType
OPT_NAME_SO_RXDATA: OptName.ValueType
OPT_NAME_SO_RCVBUF: OptName.ValueType
OPT_NAME_SO_SNDBUF: OptName.ValueType
OPT_NAME_SO_NONBLOCK: OptName.ValueType
OPT_NAME_SO_BINDTODEVICE: OptName.ValueType
OPT_NAME_SO_ERROR: OptName.ValueType
OPT_NAME_SO_LINGER: OptName.ValueType
OPT_NAME_SO_REUSEADDR: OptName.ValueType
global___OptName = OptName

class _RecvFlags:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RecvFlagsEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RecvFlags.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RECV_FLAGS_UNSPECIFIED: _RecvFlags.ValueType
    RECV_FLAGS_MSG_PEEK: _RecvFlags.ValueType

class RecvFlags(_RecvFlags, metaclass=_RecvFlagsEnumTypeWrapper):
    pass
RECV_FLAGS_UNSPECIFIED: RecvFlags.ValueType
RECV_FLAGS_MSG_PEEK: RecvFlags.ValueType
global___RecvFlags = RecvFlags

class _Shutdown:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ShutdownEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Shutdown.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SHUTDOWN_RD: _Shutdown.ValueType
    SHUTDOWN_WR: _Shutdown.ValueType
    SHUTDOWN_RDWR: _Shutdown.ValueType

class Shutdown(_Shutdown, metaclass=_ShutdownEnumTypeWrapper):
    pass
SHUTDOWN_RD: Shutdown.ValueType
SHUTDOWN_WR: Shutdown.ValueType
SHUTDOWN_RDWR: Shutdown.ValueType
global___Shutdown = Shutdown

class _SocketOptionLevel:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SocketOptionLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SocketOptionLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SOCKET_OPTION_LEVEL_UNSPECIFIED: _SocketOptionLevel.ValueType
    SOCKET_OPTION_LEVEL_SOCKET: _SocketOptionLevel.ValueType

class SocketOptionLevel(_SocketOptionLevel, metaclass=_SocketOptionLevelEnumTypeWrapper):
    pass
SOCKET_OPTION_LEVEL_UNSPECIFIED: SocketOptionLevel.ValueType
SOCKET_OPTION_LEVEL_SOCKET: SocketOptionLevel.ValueType
global___SocketOptionLevel = SocketOptionLevel

class _SocketProtocolType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SocketProtocolTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SocketProtocolType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SOCKET_PROTOCOL_TYPE_UNSPECIFIED: _SocketProtocolType.ValueType
    SOCKET_PROTOCOL_TYPE_STREAM: _SocketProtocolType.ValueType
    SOCKET_PROTOCOL_TYPE_DGRAM: _SocketProtocolType.ValueType

class SocketProtocolType(_SocketProtocolType, metaclass=_SocketProtocolTypeEnumTypeWrapper):
    pass
SOCKET_PROTOCOL_TYPE_UNSPECIFIED: SocketProtocolType.ValueType
SOCKET_PROTOCOL_TYPE_STREAM: SocketProtocolType.ValueType
SOCKET_PROTOCOL_TYPE_DGRAM: SocketProtocolType.ValueType
global___SocketProtocolType = SocketProtocolType

class IPAddress(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FAMILY_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    NET_MASK_FIELD_NUMBER: builtins.int
    PREFIX_LENGTH_FIELD_NUMBER: builtins.int
    family: global___AddressFamily.ValueType
    address: typing.Text
    net_mask: typing.Text
    prefix_length: builtins.int

    def __init__(self, *, family: global___AddressFamily.ValueType=..., address: typing.Text=..., net_mask: typing.Text=..., prefix_length: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['address', b'address', 'family', b'family', 'net_mask', b'net_mask', 'prefix_length', b'prefix_length']) -> None:
        ...
global___IPAddress = IPAddress

class GatewayAddress(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FAMILY_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    family: global___AddressFamily.ValueType
    address: typing.Text

    def __init__(self, *, family: global___AddressFamily.ValueType=..., address: typing.Text=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['address', b'address', 'family', b'family']) -> None:
        ...
global___GatewayAddress = GatewayAddress

class VirtualInterface(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    XNET_INTERFACE_NAME_FIELD_NUMBER: builtins.int
    VLAN_NAME_FIELD_NUMBER: builtins.int
    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    MAC_MTU_FIELD_NUMBER: builtins.int
    OPERATIONAL_STATUS_FIELD_NUMBER: builtins.int
    IF_INDEX_FIELD_NUMBER: builtins.int
    IP_ADDRESSES_FIELD_NUMBER: builtins.int
    GATEWAY_ADDRESSES_FIELD_NUMBER: builtins.int
    xnet_interface_name: typing.Text
    vlan_name: typing.Text
    mac_address: typing.Text
    mac_mtu: builtins.int
    operational_status: global___OperationalStatus.ValueType
    if_index: builtins.int

    @property
    def ip_addresses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPAddress]:
        ...

    @property
    def gateway_addresses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GatewayAddress]:
        ...

    def __init__(self, *, xnet_interface_name: typing.Text=..., vlan_name: typing.Text=..., mac_address: typing.Text=..., mac_mtu: builtins.int=..., operational_status: global___OperationalStatus.ValueType=..., if_index: builtins.int=..., ip_addresses: typing.Optional[typing.Iterable[global___IPAddress]]=..., gateway_addresses: typing.Optional[typing.Iterable[global___GatewayAddress]]=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['gateway_addresses', b'gateway_addresses', 'if_index', b'if_index', 'ip_addresses', b'ip_addresses', 'mac_address', b'mac_address', 'mac_mtu', b'mac_mtu', 'operational_status', b'operational_status', 'vlan_name', b'vlan_name', 'xnet_interface_name', b'xnet_interface_name']) -> None:
        ...
global___VirtualInterface = VirtualInterface

class In6Addr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDR_FIELD_NUMBER: builtins.int
    addr: builtins.bytes

    def __init__(self, *, addr: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> None:
        ...
global___In6Addr = In6Addr

class InAddr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDR_FIELD_NUMBER: builtins.int
    addr: builtins.int

    def __init__(self, *, addr: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> None:
        ...
global___InAddr = InAddr

class Addr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IPV4_FIELD_NUMBER: builtins.int
    IPV6_FIELD_NUMBER: builtins.int

    @property
    def ipv4(self) -> global___InAddr:
        ...

    @property
    def ipv6(self) -> global___In6Addr:
        ...

    def __init__(self, *, ipv4: typing.Optional[global___InAddr]=..., ipv6: typing.Optional[global___In6Addr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr', 'ipv4', b'ipv4', 'ipv6', b'ipv6']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'ipv4', b'ipv4', 'ipv6', b'ipv6']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['addr', b'addr']) -> typing.Optional[typing_extensions.Literal['ipv4', 'ipv6']]:
        ...
global___Addr = Addr

class SockAddrIn(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PORT_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    port: builtins.int

    @property
    def addr(self) -> global___InAddr:
        ...

    def __init__(self, *, port: builtins.int=..., addr: typing.Optional[global___InAddr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'port', b'port']) -> None:
        ...
global___SockAddrIn = SockAddrIn

class SockAddrIn6(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PORT_FIELD_NUMBER: builtins.int
    FLOW_INFO_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    SCOPE_ID_FIELD_NUMBER: builtins.int
    port: builtins.int
    flow_info: builtins.int

    @property
    def addr(self) -> global___In6Addr:
        ...
    scope_id: builtins.int

    def __init__(self, *, port: builtins.int=..., flow_info: builtins.int=..., addr: typing.Optional[global___In6Addr]=..., scope_id: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'flow_info', b'flow_info', 'port', b'port', 'scope_id', b'scope_id']) -> None:
        ...
global___SockAddrIn6 = SockAddrIn6

class SockAddr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IPV4_FIELD_NUMBER: builtins.int
    IPV6_FIELD_NUMBER: builtins.int

    @property
    def ipv4(self) -> global___SockAddrIn:
        ...

    @property
    def ipv6(self) -> global___SockAddrIn6:
        ...

    def __init__(self, *, ipv4: typing.Optional[global___SockAddrIn]=..., ipv6: typing.Optional[global___SockAddrIn6]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr', 'ipv4', b'ipv4', 'ipv6', b'ipv6']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'ipv4', b'ipv4', 'ipv6', b'ipv6']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['addr', b'addr']) -> typing.Optional[typing_extensions.Literal['ipv4', 'ipv6']]:
        ...
global___SockAddr = SockAddr

class AddrInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLAGS_ARRAY_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int
    FAMILY_FIELD_NUMBER: builtins.int
    SOCK_TYPE_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    CANON_NAME_FIELD_NUMBER: builtins.int

    @property
    def flags_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___GetAddrInfoFlags.ValueType]:
        ...
    flags_raw: builtins.int
    family: global___AddressFamily.ValueType
    sock_type: global___SocketProtocolType.ValueType
    protocol: global___IPProtocol.ValueType

    @property
    def addr(self) -> global___SockAddr:
        ...
    canon_name: typing.Text

    def __init__(self, *, flags_array: typing.Optional[typing.Iterable[global___GetAddrInfoFlags.ValueType]]=..., flags_raw: builtins.int=..., family: global___AddressFamily.ValueType=..., sock_type: global___SocketProtocolType.ValueType=..., protocol: global___IPProtocol.ValueType=..., addr: typing.Optional[global___SockAddr]=..., canon_name: typing.Text=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'canon_name', b'canon_name', 'family', b'family', 'flags_array', b'flags_array', 'flags_raw', b'flags_raw', 'protocol', b'protocol', 'sock_type', b'sock_type']) -> None:
        ...
global___AddrInfo = AddrInfo

class AddrInfoHint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLAGS_ARRAY_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int
    FAMILY_FIELD_NUMBER: builtins.int
    SOCK_TYPE_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int

    @property
    def flags_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___GetAddrInfoFlags.ValueType]:
        ...
    flags_raw: builtins.int
    family: global___AddressFamily.ValueType
    sock_type: global___SocketProtocolType.ValueType
    protocol: global___IPProtocol.ValueType

    def __init__(self, *, flags_array: typing.Optional[typing.Iterable[global___GetAddrInfoFlags.ValueType]]=..., flags_raw: builtins.int=..., family: global___AddressFamily.ValueType=..., sock_type: global___SocketProtocolType.ValueType=..., protocol: global___IPProtocol.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['family', b'family', 'flags_array', b'flags_array', 'flags_raw', b'flags_raw', 'protocol', b'protocol', 'sock_type', b'sock_type']) -> None:
        ...
global___AddrInfoHint = AddrInfoHint

class Linger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    L_ONOFF_FIELD_NUMBER: builtins.int
    L_LINGER_FIELD_NUMBER: builtins.int
    l_onoff: builtins.int
    l_linger: builtins.int

    def __init__(self, *, l_onoff: builtins.int=..., l_linger: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['l_linger', b'l_linger', 'l_onoff', b'l_onoff']) -> None:
        ...
global___Linger = Linger

class IPMReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IMR_MULTIADDR_FIELD_NUMBER: builtins.int
    IMR_INTERFACE_FIELD_NUMBER: builtins.int

    @property
    def imr_multiaddr(self) -> global___InAddr:
        ...

    @property
    def imr_interface(self) -> global___InAddr:
        ...

    def __init__(self, *, imr_multiaddr: typing.Optional[global___InAddr]=..., imr_interface: typing.Optional[global___InAddr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['imr_interface', b'imr_interface', 'imr_multiaddr', b'imr_multiaddr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['imr_interface', b'imr_interface', 'imr_multiaddr', b'imr_multiaddr']) -> None:
        ...
global___IPMReq = IPMReq

class IPv6MReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IPV6MR_MULTIADDR_FIELD_NUMBER: builtins.int
    IPV6MR_INTERFACE_FIELD_NUMBER: builtins.int

    @property
    def ipv6mr_multiaddr(self) -> global___In6Addr:
        ...
    ipv6mr_interface: builtins.int

    def __init__(self, *, ipv6mr_multiaddr: typing.Optional[global___In6Addr]=..., ipv6mr_interface: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['ipv6mr_multiaddr', b'ipv6mr_multiaddr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['ipv6mr_interface', b'ipv6mr_interface', 'ipv6mr_multiaddr', b'ipv6mr_multiaddr']) -> None:
        ...
global___IPv6MReq = IPv6MReq

class SockOptData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_INT32_FIELD_NUMBER: builtins.int
    DATA_BOOL_FIELD_NUMBER: builtins.int
    DATA_STRING_FIELD_NUMBER: builtins.int
    DATA_LINGER_FIELD_NUMBER: builtins.int
    DATA_IP_MREQ_FIELD_NUMBER: builtins.int
    DATA_IPV6_MREQ_FIELD_NUMBER: builtins.int
    data_int32: builtins.int
    data_bool: builtins.bool
    data_string: typing.Text

    @property
    def data_linger(self) -> global___Linger:
        ...

    @property
    def data_ip_mreq(self) -> global___IPMReq:
        ...

    @property
    def data_ipv6_mreq(self) -> global___IPv6MReq:
        ...

    def __init__(self, *, data_int32: builtins.int=..., data_bool: builtins.bool=..., data_string: typing.Text=..., data_linger: typing.Optional[global___Linger]=..., data_ip_mreq: typing.Optional[global___IPMReq]=..., data_ipv6_mreq: typing.Optional[global___IPv6MReq]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['data', b'data', 'data_bool', b'data_bool', 'data_int32', b'data_int32', 'data_ip_mreq', b'data_ip_mreq', 'data_ipv6_mreq', b'data_ipv6_mreq', 'data_linger', b'data_linger', 'data_string', b'data_string']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['data', b'data', 'data_bool', b'data_bool', 'data_int32', b'data_int32', 'data_ip_mreq', b'data_ip_mreq', 'data_ipv6_mreq', b'data_ipv6_mreq', 'data_linger', b'data_linger', 'data_string', b'data_string']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['data', b'data']) -> typing.Optional[typing_extensions.Literal['data_int32', 'data_bool', 'data_string', 'data_linger', 'data_ip_mreq', 'data_ipv6_mreq']]:
        ...
global___SockOptData = SockOptData

class AcceptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SESSION_NAME_FIELD_NUMBER: builtins.int
    SOCKET_FIELD_NUMBER: builtins.int
    session_name: typing.Text

    @property
    def socket(self) -> session_pb2.Session:
        ...

    def __init__(self, *, session_name: typing.Text=..., socket: typing.Optional[session_pb2.Session]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['session_name', b'session_name', 'socket', b'socket']) -> None:
        ...
global___AcceptRequest = AcceptRequest

class AcceptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    SOCKET_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def addr(self) -> global___SockAddr:
        ...

    @property
    def socket(self) -> session_pb2.Session:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., addr: typing.Optional[global___SockAddr]=..., socket: typing.Optional[session_pb2.Session]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr', 'socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'error_message', b'error_message', 'error_num', b'error_num', 'socket', b'socket', 'status', b'status']) -> None:
        ...
global___AcceptResponse = AcceptResponse

class BindRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...

    @property
    def name(self) -> global___SockAddr:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., name: typing.Optional[global___SockAddr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['name', b'name', 'socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['name', b'name', 'socket', b'socket']) -> None:
        ...
global___BindRequest = BindRequest

class BindResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___BindResponse = BindResponse

class CloseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> None:
        ...
global___CloseRequest = CloseRequest

class CloseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___CloseResponse = CloseResponse

class ConnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...

    @property
    def name(self) -> global___SockAddr:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., name: typing.Optional[global___SockAddr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['name', b'name', 'socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['name', b'name', 'socket', b'socket']) -> None:
        ...
global___ConnectRequest = ConnectRequest

class ConnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___ConnectResponse = ConnectResponse

class FdIsSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FD_FIELD_NUMBER: builtins.int
    SET_FIELD_NUMBER: builtins.int

    @property
    def fd(self) -> session_pb2.Session:
        ...

    @property
    def set(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[session_pb2.Session]:
        ...

    def __init__(self, *, fd: typing.Optional[session_pb2.Session]=..., set: typing.Optional[typing.Iterable[session_pb2.Session]]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['fd', b'fd']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['fd', b'fd', 'set', b'set']) -> None:
        ...
global___FdIsSetRequest = FdIsSetRequest

class FdIsSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    IS_SET_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    is_set: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., is_set: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'is_set', b'is_set', 'status', b'status']) -> None:
        ...
global___FdIsSetResponse = FdIsSetResponse

class GetAddrInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    NODE_FIELD_NUMBER: builtins.int
    SERVICE_FIELD_NUMBER: builtins.int
    HINTS_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    node: typing.Text
    service: typing.Text

    @property
    def hints(self) -> global___AddrInfoHint:
        ...

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., node: typing.Text=..., service: typing.Text=..., hints: typing.Optional[global___AddrInfoHint]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['hints', b'hints', 'stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['hints', b'hints', 'node', b'node', 'service', b'service', 'stack_ref', b'stack_ref']) -> None:
        ...
global___GetAddrInfoRequest = GetAddrInfoRequest

class GetAddrInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    RES_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def res(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AddrInfo]:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., res: typing.Optional[typing.Iterable[global___AddrInfo]]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'res', b'res', 'status', b'status']) -> None:
        ...
global___GetAddrInfoResponse = GetAddrInfoResponse

class GetNameInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    HOSTLEN_FIELD_NUMBER: builtins.int
    SERVLEN_FIELD_NUMBER: builtins.int
    FLAGS_ARRAY_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...

    @property
    def addr(self) -> global___SockAddr:
        ...
    hostlen: builtins.int
    servlen: builtins.int

    @property
    def flags_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___GetNameInfoFlags.ValueType]:
        ...
    flags_raw: builtins.int

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., addr: typing.Optional[global___SockAddr]=..., hostlen: builtins.int=..., servlen: builtins.int=..., flags_array: typing.Optional[typing.Iterable[global___GetNameInfoFlags.ValueType]]=..., flags_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr', 'stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'flags_array', b'flags_array', 'flags_raw', b'flags_raw', 'hostlen', b'hostlen', 'servlen', b'servlen', 'stack_ref', b'stack_ref']) -> None:
        ...
global___GetNameInfoRequest = GetNameInfoRequest

class GetNameInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    HOST_FIELD_NUMBER: builtins.int
    SERV_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    host: typing.Text
    serv: typing.Text
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., host: typing.Text=..., serv: typing.Text=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'host', b'host', 'serv', b'serv', 'status', b'status']) -> None:
        ...
global___GetNameInfoResponse = GetNameInfoResponse

class GetPeerNameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> None:
        ...
global___GetPeerNameRequest = GetPeerNameRequest

class GetPeerNameResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def addr(self) -> global___SockAddr:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., addr: typing.Optional[global___SockAddr]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___GetPeerNameResponse = GetPeerNameResponse

class GetSockNameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> None:
        ...
global___GetSockNameRequest = GetSockNameRequest

class GetSockNameResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def addr(self) -> global___SockAddr:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., addr: typing.Optional[global___SockAddr]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['addr', b'addr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___GetSockNameResponse = GetSockNameResponse

class GetSockOptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    LEVEL_RAW_FIELD_NUMBER: builtins.int
    OPTNAME_FIELD_NUMBER: builtins.int
    OPTNAME_RAW_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    level: global___SocketOptionLevel.ValueType
    level_raw: builtins.int
    optname: global___OptName.ValueType
    optname_raw: builtins.int

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., level: global___SocketOptionLevel.ValueType=..., level_raw: builtins.int=..., optname: global___OptName.ValueType=..., optname_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['level', b'level', 'level_enum', b'level_enum', 'level_raw', b'level_raw', 'optname', b'optname', 'optname_enum', b'optname_enum', 'optname_raw', b'optname_raw', 'socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['level', b'level', 'level_enum', b'level_enum', 'level_raw', b'level_raw', 'optname', b'optname', 'optname_enum', b'optname_enum', 'optname_raw', b'optname_raw', 'socket', b'socket']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['level_enum', b'level_enum']) -> typing.Optional[typing_extensions.Literal['level', 'level_raw']]:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['optname_enum', b'optname_enum']) -> typing.Optional[typing_extensions.Literal['optname', 'optname_raw']]:
        ...
global___GetSockOptRequest = GetSockOptRequest

class GetSockOptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    OPTVAL_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def optval(self) -> global___SockOptData:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., optval: typing.Optional[global___SockOptData]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['optval', b'optval']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'optval', b'optval', 'status', b'status']) -> None:
        ...
global___GetSockOptResponse = GetSockOptResponse

class InetAddrRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    CP_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    cp: typing.Text

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., cp: typing.Text=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['cp', b'cp', 'stack_ref', b'stack_ref']) -> None:
        ...
global___InetAddrRequest = InetAddrRequest

class InetAddrResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    addr: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., addr: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['addr', b'addr', 'error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___InetAddrResponse = InetAddrResponse

class InetAToNRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    CP_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    cp: typing.Text

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., cp: typing.Text=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['cp', b'cp', 'stack_ref', b'stack_ref']) -> None:
        ...
global___InetAToNRequest = InetAToNRequest

class InetAToNResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def name(self) -> global___InAddr:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., name: typing.Optional[global___InAddr]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['name', b'name']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'name', b'name', 'status', b'status']) -> None:
        ...
global___InetAToNResponse = InetAToNResponse

class InetNToARequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    IN_ADDR_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...

    @property
    def in_addr(self) -> global___InAddr:
        ...

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., in_addr: typing.Optional[global___InAddr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['in_addr', b'in_addr', 'stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['in_addr', b'in_addr', 'stack_ref', b'stack_ref']) -> None:
        ...
global___InetNToARequest = InetNToARequest

class InetNToAResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    address: typing.Text
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., address: typing.Text=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['address', b'address', 'error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___InetNToAResponse = InetNToAResponse

class InetNToPRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    SRC_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...

    @property
    def src(self) -> global___Addr:
        ...

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., src: typing.Optional[global___Addr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['src', b'src', 'stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['src', b'src', 'stack_ref', b'stack_ref']) -> None:
        ...
global___InetNToPRequest = InetNToPRequest

class InetNToPResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    address: typing.Text
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., address: typing.Text=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['address', b'address', 'error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___InetNToPResponse = InetNToPResponse

class InetPToNRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    AF_FIELD_NUMBER: builtins.int
    AF_RAW_FIELD_NUMBER: builtins.int
    SRC_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    af: global___AddressFamily.ValueType
    af_raw: builtins.int
    src: typing.Text

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., af: global___AddressFamily.ValueType=..., af_raw: builtins.int=..., src: typing.Text=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['af', b'af', 'af_enum', b'af_enum', 'af_raw', b'af_raw', 'stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['af', b'af', 'af_enum', b'af_enum', 'af_raw', b'af_raw', 'src', b'src', 'stack_ref', b'stack_ref']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['af_enum', b'af_enum']) -> typing.Optional[typing_extensions.Literal['af', 'af_raw']]:
        ...
global___InetPToNRequest = InetPToNRequest

class InetPToNResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    DST_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def dst(self) -> global___Addr:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., dst: typing.Optional[global___Addr]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['dst', b'dst']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['dst', b'dst', 'error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___InetPToNResponse = InetPToNResponse

class IpStackClearRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> None:
        ...
global___IpStackClearRequest = IpStackClearRequest

class IpStackClearResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___IpStackClearResponse = IpStackClearResponse

class IpStackCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SESSION_NAME_FIELD_NUMBER: builtins.int
    STACK_NAME_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    session_name: typing.Text
    stack_name: typing.Text
    config: typing.Text

    def __init__(self, *, session_name: typing.Text=..., stack_name: typing.Text=..., config: typing.Text=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['config', b'config', 'session_name', b'session_name', 'stack_name', b'stack_name']) -> None:
        ...
global___IpStackCreateRequest = IpStackCreateRequest

class IpStackCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    STACK_REF_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., stack_ref: typing.Optional[session_pb2.Session]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'stack_ref', b'stack_ref', 'status', b'status']) -> None:
        ...
global___IpStackCreateResponse = IpStackCreateResponse

class IpStackGetAllStacksInfoStrRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FORMAT_FIELD_NUMBER: builtins.int
    FORMAT_RAW_FIELD_NUMBER: builtins.int
    format: global___IPStackInfoStringFormat.ValueType
    format_raw: builtins.int

    def __init__(self, *, format: global___IPStackInfoStringFormat.ValueType=..., format_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['format', b'format', 'format_enum', b'format_enum', 'format_raw', b'format_raw']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['format', b'format', 'format_enum', b'format_enum', 'format_raw', b'format_raw']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['format_enum', b'format_enum']) -> typing.Optional[typing_extensions.Literal['format', 'format_raw']]:
        ...
global___IpStackGetAllStacksInfoStrRequest = IpStackGetAllStacksInfoStrRequest

class IpStackGetAllStacksInfoStrResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    info: typing.Text
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., info: typing.Text=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'info', b'info', 'status', b'status']) -> None:
        ...
global___IpStackGetAllStacksInfoStrResponse = IpStackGetAllStacksInfoStrResponse

class IpStackGetInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> None:
        ...
global___IpStackGetInfoRequest = IpStackGetInfoRequest

class IpStackGetInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    VIRTUAL_INTERFACES_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def virtual_interfaces(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VirtualInterface]:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., virtual_interfaces: typing.Optional[typing.Iterable[global___VirtualInterface]]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status', 'virtual_interfaces', b'virtual_interfaces']) -> None:
        ...
global___IpStackGetInfoResponse = IpStackGetInfoResponse

class IpStackOpenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SESSION_NAME_FIELD_NUMBER: builtins.int
    STACK_NAME_FIELD_NUMBER: builtins.int
    session_name: typing.Text
    stack_name: typing.Text

    def __init__(self, *, session_name: typing.Text=..., stack_name: typing.Text=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['session_name', b'session_name', 'stack_name', b'stack_name']) -> None:
        ...
global___IpStackOpenRequest = IpStackOpenRequest

class IpStackOpenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    STACK_REF_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., stack_ref: typing.Optional[session_pb2.Session]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'stack_ref', b'stack_ref', 'status', b'status']) -> None:
        ...
global___IpStackOpenResponse = IpStackOpenResponse

class IpStackWaitForInterfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STACK_REF_FIELD_NUMBER: builtins.int
    LOCAL_INTERFACE_FIELD_NUMBER: builtins.int
    TIMEOUT_MS_FIELD_NUMBER: builtins.int

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    local_interface: typing.Text
    timeout_ms: builtins.int

    def __init__(self, *, stack_ref: typing.Optional[session_pb2.Session]=..., local_interface: typing.Text=..., timeout_ms: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['stack_ref', b'stack_ref']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['local_interface', b'local_interface', 'stack_ref', b'stack_ref', 'timeout_ms', b'timeout_ms']) -> None:
        ...
global___IpStackWaitForInterfaceRequest = IpStackWaitForInterfaceRequest

class IpStackWaitForInterfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___IpStackWaitForInterfaceResponse = IpStackWaitForInterfaceResponse

class ListenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    BACKLOG_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    backlog: builtins.int

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., backlog: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['backlog', b'backlog', 'socket', b'socket']) -> None:
        ...
global___ListenRequest = ListenRequest

class ListenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___ListenResponse = ListenResponse

class RecvRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    FLAGS_ARRAY_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    size: builtins.int

    @property
    def flags_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___RecvFlags.ValueType]:
        ...
    flags_raw: builtins.int

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., size: builtins.int=..., flags_array: typing.Optional[typing.Iterable[global___RecvFlags.ValueType]]=..., flags_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['flags_array', b'flags_array', 'flags_raw', b'flags_raw', 'size', b'size', 'socket', b'socket']) -> None:
        ...
global___RecvRequest = RecvRequest

class RecvResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    MEM_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    mem: builtins.bytes
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., mem: builtins.bytes=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'mem', b'mem', 'status', b'status']) -> None:
        ...
global___RecvResponse = RecvResponse

class RecvFromRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    FLAGS_ARRAY_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    size: builtins.int

    @property
    def flags_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___RecvFlags.ValueType]:
        ...
    flags_raw: builtins.int

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., size: builtins.int=..., flags_array: typing.Optional[typing.Iterable[global___RecvFlags.ValueType]]=..., flags_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['flags_array', b'flags_array', 'flags_raw', b'flags_raw', 'size', b'size', 'socket', b'socket']) -> None:
        ...
global___RecvFromRequest = RecvFromRequest

class RecvFromResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    MEM_FIELD_NUMBER: builtins.int
    FROM_ADDR_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    mem: builtins.bytes

    @property
    def from_addr(self) -> global___SockAddr:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., mem: builtins.bytes=..., from_addr: typing.Optional[global___SockAddr]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['from_addr', b'from_addr']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'from_addr', b'from_addr', 'mem', b'mem', 'status', b'status']) -> None:
        ...
global___RecvFromResponse = RecvFromResponse

class SelectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    READFDS_FIELD_NUMBER: builtins.int
    WRITEFDS_FIELD_NUMBER: builtins.int
    EXCEPTFDS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int

    @property
    def readfds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[session_pb2.Session]:
        ...

    @property
    def writefds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[session_pb2.Session]:
        ...

    @property
    def exceptfds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[session_pb2.Session]:
        ...

    @property
    def timeout(self) -> google.protobuf.duration_pb2.Duration:
        ...

    def __init__(self, *, readfds: typing.Optional[typing.Iterable[session_pb2.Session]]=..., writefds: typing.Optional[typing.Iterable[session_pb2.Session]]=..., exceptfds: typing.Optional[typing.Iterable[session_pb2.Session]]=..., timeout: typing.Optional[google.protobuf.duration_pb2.Duration]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['timeout', b'timeout']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['exceptfds', b'exceptfds', 'readfds', b'readfds', 'timeout', b'timeout', 'writefds', b'writefds']) -> None:
        ...
global___SelectRequest = SelectRequest

class SelectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___SelectResponse = SelectResponse

class SendRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    DATAPTR_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    dataptr: builtins.bytes
    flags_raw: builtins.int

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., dataptr: builtins.bytes=..., flags_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['dataptr', b'dataptr', 'flags_raw', b'flags_raw', 'socket', b'socket']) -> None:
        ...
global___SendRequest = SendRequest

class SendResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___SendResponse = SendResponse

class SendToRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    DATAPTR_FIELD_NUMBER: builtins.int
    FLAGS_RAW_FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    dataptr: builtins.bytes
    flags_raw: builtins.int

    @property
    def to(self) -> global___SockAddr:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., dataptr: builtins.bytes=..., flags_raw: builtins.int=..., to: typing.Optional[global___SockAddr]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket', 'to', b'to']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['dataptr', b'dataptr', 'flags_raw', b'flags_raw', 'socket', b'socket', 'to', b'to']) -> None:
        ...
global___SendToRequest = SendToRequest

class SendToResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___SendToResponse = SendToResponse

class SetSockOptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    LEVEL_RAW_FIELD_NUMBER: builtins.int
    OPTNAME_FIELD_NUMBER: builtins.int
    OPTNAME_RAW_FIELD_NUMBER: builtins.int
    OPT_DATA_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    level: global___SocketOptionLevel.ValueType
    level_raw: builtins.int
    optname: global___OptName.ValueType
    optname_raw: builtins.int

    @property
    def opt_data(self) -> global___SockOptData:
        ...

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., level: global___SocketOptionLevel.ValueType=..., level_raw: builtins.int=..., optname: global___OptName.ValueType=..., optname_raw: builtins.int=..., opt_data: typing.Optional[global___SockOptData]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['level', b'level', 'level_enum', b'level_enum', 'level_raw', b'level_raw', 'opt_data', b'opt_data', 'optname', b'optname', 'optname_enum', b'optname_enum', 'optname_raw', b'optname_raw', 'socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['level', b'level', 'level_enum', b'level_enum', 'level_raw', b'level_raw', 'opt_data', b'opt_data', 'optname', b'optname', 'optname_enum', b'optname_enum', 'optname_raw', b'optname_raw', 'socket', b'socket']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['level_enum', b'level_enum']) -> typing.Optional[typing_extensions.Literal['level', 'level_raw']]:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['optname_enum', b'optname_enum']) -> typing.Optional[typing_extensions.Literal['optname', 'optname_raw']]:
        ...
global___SetSockOptRequest = SetSockOptRequest

class SetSockOptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___SetSockOptResponse = SetSockOptResponse

class ShutdownRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOCKET_FIELD_NUMBER: builtins.int
    HOW_FIELD_NUMBER: builtins.int
    HOW_RAW_FIELD_NUMBER: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    how: global___Shutdown.ValueType
    how_raw: builtins.int

    def __init__(self, *, socket: typing.Optional[session_pb2.Session]=..., how: global___Shutdown.ValueType=..., how_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['how', b'how', 'how_enum', b'how_enum', 'how_raw', b'how_raw', 'socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['how', b'how', 'how_enum', b'how_enum', 'how_raw', b'how_raw', 'socket', b'socket']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['how_enum', b'how_enum']) -> typing.Optional[typing_extensions.Literal['how', 'how_raw']]:
        ...
global___ShutdownRequest = ShutdownRequest

class ShutdownResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'status', b'status']) -> None:
        ...
global___ShutdownResponse = ShutdownResponse

class SocketRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SESSION_NAME_FIELD_NUMBER: builtins.int
    STACK_REF_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    DOMAIN_RAW_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TYPE_RAW_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    PROTOCOL_RAW_FIELD_NUMBER: builtins.int
    session_name: typing.Text

    @property
    def stack_ref(self) -> session_pb2.Session:
        ...
    domain: global___AddressFamily.ValueType
    domain_raw: builtins.int
    type: global___SocketProtocolType.ValueType
    type_raw: builtins.int
    protocol: global___IPProtocol.ValueType
    protocol_raw: builtins.int

    def __init__(self, *, session_name: typing.Text=..., stack_ref: typing.Optional[session_pb2.Session]=..., domain: global___AddressFamily.ValueType=..., domain_raw: builtins.int=..., type: global___SocketProtocolType.ValueType=..., type_raw: builtins.int=..., protocol: global___IPProtocol.ValueType=..., protocol_raw: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['domain', b'domain', 'domain_enum', b'domain_enum', 'domain_raw', b'domain_raw', 'protocol', b'protocol', 'protocol_enum', b'protocol_enum', 'protocol_raw', b'protocol_raw', 'stack_ref', b'stack_ref', 'type', b'type', 'type_enum', b'type_enum', 'type_raw', b'type_raw']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['domain', b'domain', 'domain_enum', b'domain_enum', 'domain_raw', b'domain_raw', 'protocol', b'protocol', 'protocol_enum', b'protocol_enum', 'protocol_raw', b'protocol_raw', 'session_name', b'session_name', 'stack_ref', b'stack_ref', 'type', b'type', 'type_enum', b'type_enum', 'type_raw', b'type_raw']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['domain_enum', b'domain_enum']) -> typing.Optional[typing_extensions.Literal['domain', 'domain_raw']]:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['protocol_enum', b'protocol_enum']) -> typing.Optional[typing_extensions.Literal['protocol', 'protocol_raw']]:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['type_enum', b'type_enum']) -> typing.Optional[typing_extensions.Literal['type', 'type_raw']]:
        ...
global___SocketRequest = SocketRequest

class SocketResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    SOCKET_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_NUM_FIELD_NUMBER: builtins.int
    status: builtins.int

    @property
    def socket(self) -> session_pb2.Session:
        ...
    error_message: typing.Text
    error_num: builtins.int

    def __init__(self, *, status: builtins.int=..., socket: typing.Optional[session_pb2.Session]=..., error_message: typing.Text=..., error_num: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['socket', b'socket']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error_message', b'error_message', 'error_num', b'error_num', 'socket', b'socket', 'status', b'status']) -> None:
        ...
global___SocketResponse = SocketResponse

class StrErrRRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ERRNUM_FIELD_NUMBER: builtins.int
    BUF_LEN_FIELD_NUMBER: builtins.int
    errnum: builtins.int
    buf_len: builtins.int

    def __init__(self, *, errnum: builtins.int=..., buf_len: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['buf_len', b'buf_len', 'errnum', b'errnum']) -> None:
        ...
global___StrErrRRequest = StrErrRRequest

class StrErrRResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    status: builtins.int
    error: typing.Text

    def __init__(self, *, status: builtins.int=..., error: typing.Text=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['error', b'error', 'status', b'status']) -> None:
        ...
global___StrErrRResponse = StrErrRResponse